# Site
repository: sproogen/resume-theme
# repository: Hyeongwookjung/e-commerce_analysis_platform
favicon: images/favicon.ico

# Content configuration version
version: 2  

# Personal info
name: Hyeongwook Jung
title: Data Analyst +3.5 years
email: ekam3d@gmail.com
website: https://github.com/Hyeongwookjung

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  hyeongwookjung
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ekam3d
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hyeongwook is a data analyst with 3.5+ years of experience in Samsung Electronics. He collects and analyzes enormous amount of data within the company to extract insights to improve the business. Working at three projects to improve the manufacturing process and deliver advanced management tools, he saved 100+B KRW per year for the company. He collected feedbacks from the management team and workers at the field to devise algorithms to optimize the workflow. His goal is to improve the performance of the management by applying machine learning models and verifying the consistency of the data generated by the system.

  Languages: Korean (Native), English (Business Level)
  Computer Skills: <mark>Excel</mark> <mark>Word</mark> <mark>PowerPoint</mark> <mark>Tableau</mark> <mark>Power BI</mark> <mark>Github</mark> <mark>Confluence</mark>
  Programming: <mark>Python</mark> <mark>SQL</mark> <mark>AWS</mark> <mark>HDFS</mark> <mark>R</mark>
  Technique: <mark>Machine Learning</mark> <mark>Data Mining</mark> <mark>ETL</mark> <mark>RPA</mark> <mark>Data Modeling</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/Hyeongwookjung
        # link_text: Project Website
        additional_links:
          - title:  Hyeongwookjung/e-commerce_analysis_platform
            icon: fab fa-github
            url: github.comHyeongwookjung/e-commerce_analysis_platform
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I was usually interested in analyzing e-commerce data. So I started this project with the idea of creating a data analysis platform that can help many e-commerce sellers. This platform is equipped with features that will significantly improve sellers' sales.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Samsung Electronics
        link: samsung.com
        sub_title: Data Analyst
        caption: January 2019 - Present
        # quote: >
        description: | # this will include new lines to allow paragraphs
          1. Manufacturing KPI Data Analysis Platform Development
          •	Accomplished 8+ billion KRW cost saving per year by developing a KPI data analyzing platform to assist the management team to confirm the achievement rate swiftly and establish measures in case of low KPI achievement rate: KPIs include processing cost per unit, per employee production, automation rate, and total process defection rate
          •	Saved 1.5B KRW of labor costs by creating robotic process automation (RPA) to create monthly KPI reports; replaced the manual works to make the reports with one-click report creation program with Python and implemented the program to 30 manufacturing units in different countries: decreased the report making time by 98% and achieved 0% human error (Phase 1)
          •	Achieved 98% in each KPIs by developing the 3-months future KPI achievement rate forecast algorithm to reallocate the resources more effectively such as which materials to make more purchases and where to put more workforces (Phase 2)
          •	Won 98.1%, 96.6%, and 95.2% KPI forecast accuracy rate respectively for the coming three months by establishing the KPI data analysis platform with a dashboard, made with Tableau, for real-time monitoring (Phase 3)

          2. Abnormality Detection System Development to Improve the Injection Process 
          •	Reduced the defection rate due to errors in injection process from 13% to 4% by developing an abnormality detection system
          •	Alarmed the managers of possible defection by letting the machine to learn the conditions that generate defections with machine learning: collected large data from 29 injectors, managed them in data lake, allowed the server to learn how to detect abnormalities in real time, and alerted the injection with abnormal conditions to the managers
          •	Advanced the detecting rate to 89% from 75% by improving the data processing: simplified the process with principal component analysis, removed unstable data, and assigned weighted value for highly correlated data affecting post processing

          3. Mold Life Prediction System Development
          •	Decreased the yearly mold repair cost by 20B KRW, from 100B to 80B, by developing the mold life prediction system
          •	Developed the system with Python using machine learning based algorithms and dashboards to alarm the managers the life expectancy of the mold, required spare parts, and the possible breakdown of the mold after certain amount of shots
          •	Improved the data matching accuracy from 20% to 80% by translating sentences of the repair reasons entered by the workers into natural language for precise analysis and categorization of the mold repairment and disposal data
      - layout: left
        title: Samsung Electronics
        link: samsung.com
        sub_title: Mold Design Engineer
        caption: November 2014 - December 2018
        # quote: >
        description: 
          •	Improved the efficiency during the reel exchange process by creating the Multi-Layer Ceramic Capacitor (MLCC) Infinite Supply Bulk Feeder which can continuously supply the MLCC when the bulk feeder is placed into the rear of the machine
          •	Achieved the following specifications with the technology 0.06sec cycle time, micro size part with MLCC 1005 size with 1mm width, 0.5mm column, and height
          •	Contributed to producing 300K units of Galaxy Gear S2 in a year at Vietnam by developing a forging method in six months

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ajou University
        caption: 2019 - 2022
        sub_title: Convergence Systems Engineering
        quote: > 
          Project: Analysis of shopping trends using e-commerce data
        description: | # this will include new lines to allow paragraphs
          - Using Machine Learning to Create a Model for Forecasting Sales and Competitive Strength by Category
          - Analyze the user's log data with a/b test to determine the optimal setting value

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Swimming
      - Going on a trip

# Footer
footer_show_references: False
# references_title: References on request (Override references text)

# Build settings
# remote_theme: Hyeongwookjung/e-commerce_analysis_platform
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
